Adding Matrices and Adding Scalars

In [1]:
import numpy as np

In [2]:
5+5 #example of adding scalars together

10

In [3]:
10+4

14

Adding matrices

In [11]:
m1 = np.array([[5,12,6],[-1,0,14]])
m2= np.array([[6,13,8],[-5,0,18]])
m1

array([[ 5, 12,  6],
       [-1,  0, 14]])

In [14]:
m3= np.array([6,13,12])
m3

array([ 6, 13, 12])

In [15]:
m1+m3 #found out that I can add a vector of the same length as a matrix ie if the vector
# has a length of 3 elements and the matrix has two or 3 rows that fit the same amount of elements

array([[11, 25, 18],
       [ 5, 13, 26]])

In [16]:
m4 = np.array([12,13])

In [17]:
m1+m4

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

Can't add vectors of different element lengths together

Scalar exceptions

In [19]:
m1 +1 # added a scalar to a matrix and all elements incraesed by 1

array([[ 6, 13,  7],
       [ 0,  1, 15]])

In [20]:
scores = np.array([[53, 32, 103], [43, 56, 78], [78, 96, 123], [61, 43, 65]])

In [21]:
updated_scores = scores +36 #adding scalar to each matrix element. Makes sense in python
#in linear algebra not so much

In [22]:
print(updated_scores)

[[ 89  68 139]
 [ 79  92 114]
 [114 132 159]
 [ 97  79 101]]



The shape of the matrix scores is (4, 3).(the dimensions 4x3)

In simple terms:

It has 4 rows (horizontal sets of numbers).
It has 3 columns (vertical sets of numbers).

Transpose a matrix and vectors

In [27]:
v1 = np.array([1,2,3])
v1

array([1, 2, 3])

we dont lose info when we transpose and if transposed twice we return the original vector

In [32]:
v1.T # one dimensional arrays do mot get transposed in python
#can use v1.reshape to transpose the vector/change it from a row to a column

array([1, 2, 3])

In [30]:
a = np.array([[3,5],[-2,4]])
a

array([[ 3,  5],
       [-2,  4]])

In [31]:
a.T #Transpose a matrix

array([[ 3, -2],
       [ 5,  4]])

In [37]:
v1_reshaped = v1.reshape(1,3)
v1_reshaped

array([[1, 2, 3]])

In [36]:
v1_reshaped.T #Now we can transpose the vector because we reshaped it

array([[1],
       [2],
       [3]])

Multiplication of vectors

In [38]:
#we use dot product /inner or scalar products when multiplying for vectors and matrices

DOT PRODUCT

In [39]:
x =np.array([2,3,4])
t = np.array([2,4,5])

In [41]:
np.dot(x,t)

36

In [42]:
#multiplying two vectors will result in a  scalar being an output
# the will multiply the vector elements together then add the results

Multiplying a scalar with a vector

In [43]:
x

array([2, 3, 4])

In [50]:
x.shape

(3,)

In [45]:
5*x # all components will be multiplied if we multiply a scalar with a vector
# changes the scale of the vectors and not the shape

array([10, 15, 20])

In mathematics, two vectors are considered orthogonal (perpendicular) if their dot product is zero.
You are provided with 4 vectors defined in NumPy. Compute the dot product for each pair of vectors and determine which pair, if any, is orthogonal. As the final output, print the vector with the smaller index from the orthogonal pair.

what this means is that I need to multiply out the vectors then add my results to see if any pair of vectors results in a zero. After THAT we need to print out which vector comes first in this perpendicular series. ie v2*v4 would need me to print v2

In [46]:
# Vectors
v1 = np.array([3, -1, -2, 3])
v2 = np.array([-2, 5, 7, 1])
v3 = np.array([5, 3, 1, -4])
v4 = np.array([3, 2, -0, -4])



In [48]:
v2*v4# this result gives us zero 

array([-6, 10,  0, -4])

In [49]:
print(v2)

[-2  5  7  1]
