Import all the relevant libraries

In [5]:
import numpy as np #using numpy libraries will allow for us to create vectors and scalars in Python(arrays)

Scalar

Mathematics uses relation to understand certain things. Two lines that are not in the same direction can be considered a vector
An array is also a a matrix
A matrix is a different form of a vector(a vector is a special case of a matrix)
Amn is how a  matrix reads (You can read it from m = rows and n = said amount of columns in the matrix)
Vectors are 2D in dimension(the ones we are dealing with at the moment)

In [2]:
s=5

In [3]:
s

5

Vectors

In [7]:
v = np.array([5,-2,4])

In [8]:
v

array([ 5, -2,  4])

Matrix

In [9]:
n = np.array([[5,12,6],[-3,0,14]])

In [10]:
n

array([[ 5, 12,  6],
       [-3,  0, 14]])

Data Types

In [11]:
type(s)

int

In [12]:
type(v)

numpy.ndarray

In [14]:
type(n)

numpy.ndarray

The v one is a one dimensional array and the n one is a two dimensional array

In [16]:
s_array = np.array(5)

In [17]:
s_array

array(5)

This is if we wanna turn our scalar component into a vector

Data Shape


In [20]:
n.shape #expected result because we have a 2 by 3 matrix (2 rows and 3 columns)

(2, 3)

In [21]:
v.shape

(3,)

In [24]:
v.reshape(1,3) #we are chaning the vector into a different fromat (can be from 3 rows 
#one columns or 1 row and 3 columns

array([[ 5, -2,  4]])

In [ ]:
#scalar has no shape as it has one dimension only