In [3]:
import numpy as np

Creating a Tensor

In [4]:
m1 = np.array([[2, 3], [-1, 4]])
m2 = np.array([[1,8], [0,1]])
m3 = np.array([[-3, -4], [6, 4]])

In [9]:
t = np.stack((m1,m2,m3)) #can also use np.array to do this

In [7]:
t

array([[[ 2,  3],
        [-1,  4]],

       [[ 1,  8],
        [ 0,  1]],

       [[-3, -4],
        [ 6,  4]]])

In [8]:
t2= np.array((m1,m2,m3))
t2

array([[[ 2,  3],
        [-1,  4]],

       [[ 1,  8],
        [ 0,  1]],

       [[-3, -4],
        [ 6,  4]]])

In [10]:
print(t.shape)

(3, 2, 2)


Adding and Substracting Vectors and Matrices

You would first declare the matrix or vector then simply add/subtract the assigned variables from each other

In [12]:
m1-m2 #they neeed to be the same dimensions in order for the arithmetic operations to work

array([[ 1, -5],
       [-1,  3]])

In [13]:
#Provided with these vectors,perform aritmetic operations on the eligible vectors

v1 = np.array([3, 7, 9, 4])
v2 = np.array([-1, 5, 2, 0, -5])
v3 = np.array([-2, -7, 9, 13])


In [14]:
v_sum = v1+v3

print(v_sum)

[ 1  0 18 17]


Matrices can have arithmetic operations performed on them if they are the same dimensions
Vectorsa can have arithmetic operations performed on them if they are the same length/have the same elements